name: CI build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout del repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Configurar Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      # 3️⃣ Build del proyecto
      - name: Build project
        run: ./mvnw clean compile -B

      # 4️⃣ Ejecutar pruebas unitarias
      - name: Run tests
        run: ./mvnw test -B

      # 5️⃣ Generar reporte de cobertura Jacoco
      - name: Generate Jacoco report
        run: ./mvnw jacoco:report -B

      # 6️⃣ Subir reporte como artifact
      - name: Upload Jacoco report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco/
